# docker-compose run web rails new . --force --database=mysql
# docker run --rm rails-web ls -la /app
# docker-compose build 
# up 
# database.yml
# http://localhost:3000/

#  docker-compose run web bin/rails g scaffold User name:string
# docker-compose run web bundle exec rails db:migrate
# docker-compose down
# docker-compose up
#---次回-------------
# docker-compose up
# docker-compose run web rake db:create
# docker-compose run web bundle exec rails db:migrate
# docker-compose up

version: '3'

services:
  web:
    build: .
    command: bundle exec rails server -p 3000 -b 0.0.0.0
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - db
    tty: true
    stdin_open: true
  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - db-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
volumes:
  db-volume: